### ISSUE TITLE
Create a simple process for updating itwêwina dictionary content

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#258]
Creating a more permanent solution for #255, since CW is being continuously updated, and we will be expanding MD based on the Cree recordings (and this involves a gradually increasing number of these spoken snippets matching dictionary entries), we would want a simple, straight-forward process for updating our crk lexical database providing content for itwêwina.

In this, we'd want some diagnostics as well.

**Comment by aarppe** [comment]
@Madoshakalaka Based on today's discussion, this meta-issue should concern the following more specific tasks (these can be modified to be coding-wise more accurate):

- [ ] monitor the ALTLab repository for changes to `crkeng.xml`.
- [ ] automatically attempt importing `crkeng.xml` if that has been changed.
- [ ] check that tests are passed successfully before replacing old crk dictionary content within itwêwina, and deploying this new content.
- [ ] if tests are unsuccessful, keep to the previously imported crk dictionary content within itwêwina.

**Comment by eddieantonio** [comment]
@Madoshakalaka please prepare:

 - [ ] PR for just-in-time database generation
 - [ ] PR for a management command, that when invoked, attempts to update `crkeng.xml`

**Comment by aarppe** [comment]
@andrewdotn I believe this has now in practice been implemented with incremental import? Whatever remains might be commented here, but otherwise this and the associated issues can be considered closed?

**Comment by andrewdotn** [comment]
The process for getting changes into the dictionary into production is documented [here](https://morphodict.readthedocs.io/en/latest/developers-guide.html?highlight=hour#importing-dictionaries) and [here](https://github.com/UAlbertaALTLab/crk-db/tree/main#steps-to-incrementally-update-the-production-database). I will add a link from the first to the second.

It is definitely feasible to very quickly make small changes to the dictionary. When the generation or phrase translation FSTs are updated, or when the set of paradigm cell templates is changed, a bigger reimport should be done, but it’s the same command with a different flag that just takes longer: about an hour. But you can start it and then check back later to see if it finished ok, you don’t have to bring the site down or do any extra manual steps at the end.

The process could definitely be streamlined and automated in the future.
