### ISSUE TITLE
Create straight-forward processes for updating dictionary FSTs and DB sources

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#325]
Going forward, we would need to have in place straight-forward processes by which the analysis and generation FSTs and the dictionary database source(s) can be updated and the results diagnosed and validated (starting with `crk`). The diagnostics are needed to ensure that the new FSTs and new dictionary source do not break any instance of our intelligent dictionaries.

- [ ] update process in place for dictionary FSTs, for descriptive analysis and normative generation (also made use of in the generation of full paradigms for all entries in the dictionary source). Specified in #257.
- [ ] diagnostics in place for checking that updated FSTs work with enumerated test cases. Specified in #257.
- [ ] update process in place for (crk) dictionary source. Specified in #258.
- [ ] diagnostics in place for checking that dictionary source works with enumerated test cases. Specified in #258.

**Comment by aarppe** [comment]
@andrewdotn I believe this has now in practice been implemented with or in conjunction with incremental import? Whatever remains might be commented here, but otherwise this and the associated issues can be considered closed?

**Comment by andrewdotn** [comment]
See https://github.com/UAlbertaALTLab/morphodict/issues/258#issuecomment-932613386
