### ISSUE TITLE
Overview with meta-issues for second milestone version

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#346]
The following are an overview of improvements to be implemented in the **second** milestone version of itwêwina:
(**EDITED** - moved a number of issues/features to third release, so this list represents the complete set of current priorities)

- [x] 1. Recordings
   - [x] Show all recordings pertinent to a dictionary entry, exhibiting speaker/community information (#347)
   - [x] implement links to speaker pages (#259)
   - [x] make recordings available on search results page (#404) 
   - [x] Improve presentation of multiple recordings and links to speaker pages, taking inspiration from UX design (#422, #541 moved to third milestone)
- [x] 2. Backend updating and refactoring
   - [x] Implement simple, automated processes for updating (#325) both FSTs (#257) and dictionary DB (#258) in _itwêwina_, when these are revised, and do away with `engcrk.xml` (#385) [Maybe DB/XML updating #258 will become automated in 2nd milestone, and FST updating #257 in 3rd milestone?]
   - [x] Make the generation of paradigms more effective (JIT instead of AOT: #389).
   - [x] Separate language-specific from language-agnostic code. (#463) [this can be continued in the 3rd milestone]
- [x] 3. Paradigms and inflection information
   - [x] Systematize presentation of (inflected) word-form and dictionary entry head word information (#399)
   - [x] Show inflectional categories (#101, #358, #434).
   - [x] Show morpheme boundaries (#397), as an option (#398)
   - [x] Improve relabeling (#266): with feature sequences (#348)
   - [x] Improve relabeling: prefixal features (#373)
   - [x] Improve relabeling: apply three-way options throughout, not only in paradigm layouts but also in the presentation of the linguistic analysis and of lexical information (#1047).
   - [x] Improve relabeling: show the stem instead of the lemma (#235, #475).
   - [x] Improve paradigm presentation when cells/rows are missing. (#111, #169, #194, #505)
   - [x] Show in paradigms whether an inflected word-form has been observed or not. (#455)
   - [x] Improve presentation of paradigm cells with multiple word-forms (#507).
   - [x] Reorganize paradigm layouts as more intuitive to look up. (#131, #193, #473, #476)
   - [x] Revise basic paradigms to match new representation of tense with preverb tags. (#392)
- [x] 4. Search
   - [x] Implement prefix search for Cree (#133)/
   - [x] Implement prefix search for English (#142).

- [x] 5. DIctionary source presentation and selection
   - [x] Provide in tooltip full source data for acronyms, and links as well (CW, MD, and AE) (#393)
   - [x] Implement selection of dictionary source (any combination of CW vs. MD vs. AE) (#126).

- [ ] Miscellaneous house-keeping
   - [ ] Implement full set of options 

Various bugs at the tail end of the Current issues can be fixed as well, if the work gets stalled.

**Comment by aarppe** [comment]
Realized there were some lingering house-keeping issues pertaining to the main ones that we'd want to cover under this current release.
