### ISSUE TITLE
Implement settings menu/page for selecting interface/functionality options

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#708]
So that users – language instructors, learners, community members, linguists – can choose exactly the functionality, dictionary sources, and labeling as well as othe behavior that they want, we should implement the following settings menu/window for selecting among all the options:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/15003407/111917665-ea689b80-8a46-11eb-96a4-e8e7f6e7020e.png">

Some of Cree terms yet need some validation by Jean / Arok.

**Comment by aarppe** [comment]
A task-oriented listing:
---
- [ ] **Interface language / ohtiskawi-ayamiwin**
   - [ ]	nêhiyawêwin / Plains Cree 
   - [ ]	English / âkayâsîmowin
---
- [ ] **Dictionary sources / itwêwasinahikana**
   - [ ]	Cree : Words / nêhiyawêwin : itwêwina
   - [ ]	Maskwacîs Cree Dictionary / nêhiyaw-pîkiskwêwinisa
   - [ ]	Alberta Elders’ Cree Dictionary / alperta ohci kêhtê-ayak nêhiyaw otwêstamâkêwasinahikan
---
- [ ] **Labels / tânisi ê-wîhcikâtêki**
   - [ ]	linguistic / kanawâpahtamowin ayamiwina
   - [ ]	plain English / mosci-âkayâsîmowin
   - [ ]	nêhiyawêwin / Plains Cree
   - [ ]	emojis / cikâstêpisona
---
- [ ] **Behavior / isîhtwâwin**
   - [ ]	show morpheme boundaries / wâpahtahin tânisi itwêwin ê-pâh-piskihcayâk icwêwinisihk
 	icwêwinisa 
   - [ ]	show Cree words translated into English phrases / wâpahtahin tânisi âkayâsîwastâniwan nêhiyawi-itwêwina âkayâsîwi-pîkiskwêwinihk
   - [ ]	show synthesized pronunciations of Cree words / wâpahtahin tânisi âpacihcikan nêhiyawi-itwêwina ê-itahk
---

**Comment by aarppe** [comment]
Based on our Tech Team meeting discussion, the desired order of implementation would be the following, in part due to "customer" demand and in part due to the necessary components already being implemented:
1. Labels (making use of [crk.altlabel.tsv](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/master/CreeDictionary/res/crk.altlabel.tsv))
2. Dictionary sources (among currently existing ones, CW vs. MD, for now)
3. Behavior + Interface <-- since these require further backend + frontend + linguistic work

**Comment by eddieantonio** [comment]
@aarppe: there's no way I will be able to implement this feature by the end of this week, and I'm off next week. I suggest we deliver this feature in tiny, incremental chunks. I have grand ideas for how the final product should look like, but I think at first, a toggle that enables "traditional/linguist mode" and one that enables "beginner mode".

In *later* iterations, we can customize each and every setting. e.g., I personally want full inflectional class descriptions AND emoji, because the emoji help me scan results a lot quicker.

**Comment by aarppe** [comment]
@eddieantonio I can imagine that this wouldn't necessarily happen quickly, but finally getting started on it is good enough. Having two overarching modes that implement and aggregate a set of settings was one of the suggestions in implementing optionality, so we can well start with that. But on the longer term I would really want to see full optionality (configurable via such a settings page/pop-up) so that users can choose exactly and specifically what they want. For instance, I could imagine that one could select multiple alternatives for an option, say just linguistic labels, or just emojis, or both linguistic labels and emojis - the settings page would allow for that.

**Comment by eddieantonio** [comment]
> Would the pop-ups be in reverse?
> 
> That is, for the community mode, what you see initially is 1) the emojis and the 'like: X' text, and secondarily in the pop-up 2) the linguistic labels (long 'regular transitive animate verb' and short '(VTA-1)').
> 
> And for the linguistic mode, you'd initially see 1) the short linguistic label, e.g. VTA-1, and below that the full linguistic label 'regular transitive animate verb', but then secondarily in the pop-up 2) the example word case 'like: XXX' (but perhaps not the emoji).
> 
> Eventually I'd think we'd want to include the nêhiyawêwin labels in the mix.

_Originally posted by @aarppe in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/729#issuecomment-820635266_

@aarppe: could you please illustrate what you mean here? #729 was a way to get a quick turnaround for the customization (so that you have something to show AED!)

**Comment by aarppe** [comment]
The linguist mode could work as it is, with the pop-up, but for the community mode you'd see something like the following in the pop-up (i.e. the example case in _**like: wîcihêw**_):

<img width="367" alt="image" src="https://user-images.githubusercontent.com/15003407/114920623-dbc39900-9de6-11eb-9f6b-b501240ad6aa.png">

**Comment by dwhieb** [comment]
Arok sent us a revised version of the Plains Cree translations of the interface. I've updated this comment with the new translations:

https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/708#issuecomment-807877843

**Comment by aarppe** [comment]
@nienna73 Now that we have more things to choose on our options page, we could implement that bilingually as specified in the comment about: https://github.com/UAlbertaALTLab/morphodict/issues/708#issuecomment-807877843

**Comment by aarppe** [comment]
With the exception of the interface language, the options have been implemented, though we still would want to provide Cree translations alongside the English option texts (#1137).
